### ISSUE TITLE
Add --dependencies to click-odoo-initdb

### ISSUE THREAD

**Issue by Yajo** [acsone/click-odoo-contrib#74]
Sometimes you want to test the installation of a module, so you're interested in preinstalling all of its dependencies but not the module itself.

IMHO it would be great to be able to do it like `click-odoo-initdb -dn devel -m module`.

Do we have a script that detects a module's dependencies? I guess that would be a good starting point after all...

**Comment by sbidoul** [comment]
@Yajo that logic to find transitive dependencies of a module is indeed buried in several places. click-odoo-initdb has itn MQT has it, etc. 

I've long been thinking about creating a project ( `manifestoo?) with an API and an CLI to inspect and manipulate addons manifests based on an addons-path.

That should be another project and it will not depend on click-odoo because it is useful without an installed Odoo, and does not really require it.

Things it could do:
- list (installable) addons ([inspiration](https://github.com/OCA/oca-github-bot/blob/master/src/oca_github_bot/manifest.py))
- find transitive dependencies ([inspiration](https://github.com/acsone/acsoo/blob/master/acsoo/addons.py))
- detect license compatibility issues
- ...

**Comment by Yajo** [comment]
I think a script here would fit perfectly, TBH.

I have [a script in doodba that does that in just a few lines](https://github.com/Tecnativa/doodba/blob/5a5d94dc42e6afa7d1b29eb2ab16c11ed83924ee/bin/addons#L119-L127). Of course it's not usable outside doodba, but I mean that it would be a ridiculous amount of code to justify a separate project IMHO.

To add it here, we could just add a shared function and a script that exposes it. Personally as I install click-odoo-contrib in doodba, it should be just enough. For MQT I guess it could be installed there too, so...

Well, just one opinion... if you prefer you can do that manifestoo separately of course.

**Comment by sbidoul** [comment]
Manifestoo now provides this feature: `manifestoo --select myaddon list-depends --transitive`.
